spring.application.name=demo

# ===== BASE DE DATOS =====
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_electronicos?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== JWT =====
jwt.secret=claveUltraSecretaParaFirmarJWTToken2026SistemaElectronicos
jwt.expiration=86400000

# ===== LOGGING =====
logging.level.com.example.demo=DEBUG
